### PR TITLE
[WIP] #89 Adapt analytic items visualization

### PR DESCRIPTION
**Pull request by austininseoul**

### CODE REVIEW

**Review by jmformenti — COMMENTED** [review]
@austininseoul could you explain which issue is being implemented in this PR? and how can it be tested?

**Comment by austininseoul** [comment]
[TO REFINE] Adapt analytic items visualization #89 @jmformenti

**Comment by jmformenti** [comment]
> [TO REFINE] Adapt analytic items visualization #89

@austininseoul We need to further refine this topic with @faulhaber  to better understand the expected view, if you have a chance, please go ahead. In the meantime, I'll mark the PR with WIP = work in progress.

**Comment by faulhaber** [comment]
I believe that this problem (being able to display CNUM and COPID) can only be solved by refining the SPARQL queries for TEXID and MANID. The SPARQL query for TEXID must also search for the search term in CNUM. Once a TEXID (Work) search returns a record, the resulting display should show the data for TEXID followed by the data for CNUM. See e.g. [BETA texid 1001](https://philobiblon.upf.edu/xtf/servlet/org.cdlib.xtf.dynaXML.DynaXML?source=unified/Display/1001BETA.Work.xml&style=Work.xsl%0A%0A%20%0A%20%0A%20&gobk=http%3A%2F%2Fphilobiblon.upf.edu%2Fxtf%2Fservlet%2Forg.cdlib.xtf.crossQuery.CrossQuery%3Frmode%3Dphilobeta%26everyone%3Dtexid+1001%26creator%3D%26title%3D%26incipit%3D%26explicit%3D%26assocname%3D%26daterange%3D%26placeofcomposition%3D%26subject%3D%26text-join%3Dand%26browseout%3Dwork%26sort%3Dmoniker).  The SPARQL query for MANID must also search for the search term in BOTH CNUM and COPID.  Similarly, once a MANID (MsEd) search returns a record, the resulting display should show the data for MANID followed by the data for CNUM followed by the data for COPID, e.g.: [MANID 1050](https://philobiblon.upf.edu/xtf/servlet/org.cdlib.xtf.dynaXML.DynaXML?source=unified/Display/1050BETA.MsEd.xml&style=MsEd.xsl%0A%0A%20%0A%20%0A%20&gobk=http%3A%2F%2Fphilobiblon.upf.edu%2Fxtf%2Fservlet%2Forg.cdlib.xtf.crossQuery.CrossQuery%3Frmode%3Dphilobeta%26mstype%3DP%26everyone%3Dcopid+1001%26city%3D%26library%3D%26shelfmark%3D%26daterange%3D%26placeofprod%3D%26scribe%3D%26publisher%3D%26prevowner%3D%26assocname%3D%26subject%3D%26text-join%3Dand%26browseout%3Dmsed%26sort%3Dtitle).

**Comment by jmformenti** [comment]
Deprecated

**Pull request closed without merging**
